### ISSUE TITLE
Browser closed unexpectedly

### ISSUE THREAD

**Issue by vpier111** [qtchaos/py_mega_account_generator#13]
I'm encountering an error when running:

```
Retrying mail.tm account generation...
Traceback (most recent call last):
  File "C:\Users\viper\py_mega_account_generator\main.py", line 138, in <module>
    asyncio.run(register(asyncio.run(generate_mail())))
  File "C:\Users\viper\AppData\Local\Programs\Python\Python39-32\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\viper\AppData\Local\Programs\Python\Python39-32\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\viper\py_mega_account_generator\main.py", line 56, in register
    browser = await pyppeteer.launch({
  File "C:\Users\viper\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pyppeteer\launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "C:\Users\viper\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pyppeteer\launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "C:\Users\viper\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pyppeteer\launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:


C:\Users\viper\py_mega_account_generator>
```

What could be the causation?

**Comment by qtchaos** [comment]
Are you using a chromium based browser? If i can recall this happens if you try to use Firefox.

**Comment by j0hnckuy** [comment]
Same error here,

```
Traceback (most recent call last):
  File "C:\Python310\py_mega_account_generator-master\main.py", line 138, in <module>
    asyncio.run(register(asyncio.run(generate_mail())))
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Python310\py_mega_account_generator-master\main.py", line 56, in register
    browser = await pyppeteer.launch({
  File "C:\Python310\lib\site-packages\pyppeteer\launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "C:\Python310\lib\site-packages\pyppeteer\launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "C:\Python310\lib\site-packages\pyppeteer\launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:
```

I am using Chrome on my system.

**Comment by qtchaos** [comment]
Could one of you send a screenshot of your `settings.json`?

**Comment by qtchaos** [comment]
Update to the latest version and this is fixed :)
