### ISSUE TITLE
Hmmmm.

### ISSUE THREAD

**Issue by DogancanYr** [qtchaos/py_mega_account_generator#14]
```
PS C:\Users\Dogan\Desktop\py_mega_account_generator-master> python main.py
Traceback (most recent call last):
  File "C:\Users\Dogan\Desktop\py_mega_account_generator-master\main.py", line 8, in <module>
    from utilities.etc import p_print, clear_console, Colours, clear_tmp, reinstall_tenacity, check_for_updates, delete_default
  File "C:\Users\Dogan\Desktop\py_mega_account_generator-master\utilities\etc.py", line 7, in <module>
    from mega import Mega
  File "C:\Users\Dogan\AppData\Local\Programs\Python\Python312\Lib\site-packages\mega\__init__.py", line 1, in <module>
    from .mega import Mega  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dogan\AppData\Local\Programs\Python\Python312\Lib\site-packages\mega\mega.py", line 18, in <module>
    from tenacity import retry, wait_exponential, retry_if_exception_type
  File "C:\Users\Dogan\AppData\Local\Programs\Python\Python312\Lib\site-packages\tenacity\__init__.py", line 451, in <module>
    from tenacity._asyncio import AsyncRetrying
  File "C:\Users\Dogan\AppData\Local\Programs\Python\Python312\Lib\site-packages\tenacity\_asyncio.py", line 33, in <module>
    class AsyncRetrying(BaseRetrying):
  File "C:\Users\Dogan\AppData\Local\Programs\Python\Python312\Lib\site-packages\tenacity\_asyncio.py", line 41, in AsyncRetrying
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?
```

**Comment by DogancanYr** [comment]
Python 3.10.0 necessary .
