### ISSUE TITLE
ModuleNotFoundError: No module named 'tenacity._asyncio'

### ISSUE THREAD

**Issue by vpier111** [qtchaos/py_mega_account_generator#16]
Hi, I recently filed a bug report from my desktop, and the latest update fixed the bug, however when I try to use this script on my laptop, I keep getting an error. I have run all the required commands, including installing the required modules, and have also tried repairing python, none of which worked. Here is a full log of my terminal:

```
Microsoft Windows [Version 10.0.19045.3570]
(c) Microsoft Corporation. All rights reserved.

C:\Users\viper\py_mega_account_generator>python main.py
Traceback (most recent call last):
  File "C:\Users\viper\py_mega_account_generator\main.py", line 8, in <module>
    from utilities.etc import p_print, clear_console, Colours, clear_tmp, reinstall_tenacity, check_for_updates, delete_default
  File "C:\Users\viper\py_mega_account_generator\utilities\etc.py", line 7, in <module>
    from mega import Mega
  File "C:\Users\viper\AppData\Local\Programs\Python\Python312\Lib\site-packages\mega\__init__.py", line 1, in <module>
    from .mega import Mega  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\viper\AppData\Local\Programs\Python\Python312\Lib\site-packages\mega\mega.py", line 18, in <module>
    from tenacity import retry, wait_exponential, retry_if_exception_type
  File "C:\Users\viper\AppData\Local\Programs\Python\Python312\Lib\site-packages\tenacity\__init__.py", line 451, in <module>
    from tenacity._asyncio import AsyncRetrying
ModuleNotFoundError: No module named 'tenacity._asyncio'

C:\Users\viper\py_mega_account_generator>
```

It seems this is only an issue on my laptop, so it may be an issue on my end.

**Comment by qtchaos** [comment]
Try using Python 3.10, one of the dependencies is pretty old and doesn't like the newer versions of Python.

**Comment by qtchaos** [comment]
Ideally we wouldn't have to deal with this so I'll leave the issue open for now.

**Comment by touhamii** [comment]
i always have to go back to install python 3.10  )=

**Comment by stuffed18** [comment]
i figured out how to get this to work on the latest version of python!
you need to make some minor modifications to the tenacity library. 
1. Downgrade the tenacity library to version 5.1.5
`pip uninstall tenacity`
`pip install tenacity==5.1.5`
2. Locate the tenacity/_asyncio.py file (for me, it was in `C:\Users\[USER]\AppData\Local\Programs\Python\Python312\Lib\site-packages\tenacity\_asyncio.py`).
3. i cant remember what the function was called, so i just called it my_function here, but replace:
```
@asyncio.coroutine
def my_function(...):
```
with
`async def my_function(...):` 
two lines become one line
4. ctrl-f for `yield from` (it appears twice) and replace it with `await`
