### ISSUE TITLE
Already been asked & resolved before and I'm using the latest version which shall counter this problem already but here is it - [pyppeteer.errors.TimeoutError]

### ISSUE THREAD

**Issue by j0hnckuy** [qtchaos/py_mega_account_generator#19]
Hello mate,

Got this error.

`Failed to clear temporary files... killing previous instances.
Killing process msedgewebview2.exe...
Killing process msedge.exe...
Killed previous instances successfully!
Failed to clear temporary files... killing previous instances.
Killing process msedgewebview2.exe...
Killed previous instances successfully!
Registered account successfully!
Retrieved mail successfully!
Found mail!
Traceback (most recent call last):
  File "P:\py_mega_account_generator-master(2)\py_mega_account_generator-master\main.py", line 138, in <module>
    asyncio.run(register(asyncio.run(generate_mail())))
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "P:\py_mega_account_generator-master(2)\py_mega_account_generator-master\main.py", line 76, in register
    await initial_setup(context, message, credentials)
  File "P:\py_mega_account_generator-master(2)\py_mega_account_generator-master\utilities\web.py", line 43, in initial_setup
    await confirm_page.waitForSelector("#freeStart", timeout=1000)
  File "C:\Python310\lib\site-packages\pyppeteer\frame_manager.py", line 855, in __await__
    raise result
pyppeteer.errors.TimeoutError: Waiting for selector "#freeStart" failed: timeout 1000ms exceeds.`

I haven't created even 1 account so far - to answer the question you asked the other user with this same issue.

Thanks for reading.

**Comment by DogancanYr** [comment]
Is this site open for you? https://mail.tm or you can download chrome.

**Comment by j0hnckuy** [comment]
I can browse the website. I've chrome. What to do next?

**Comment by DogancanYr** [comment]
Download the account generator again.
When it cannot reach the site within 1000 ms, it gives this error. We set this time to 10000 ms.

**Comment by j0hnckuy** [comment]
okay, trying.

**Comment by DogancanYr** [comment]
Code => download zip or download from the Instructions section, download the project from here click on the text, the relase section has not been updated.

**Comment by j0hnckuy** [comment]
yeah did that. it didnt work.

**Comment by DogancanYr** [comment]
Write the error again.

**Comment by j0hnckuy** [comment]
It worked. I had to open CMD as admin. I was about to edit my previous post and your message popped up. thank you for helping.

**Comment by DogancanYr** [comment]
Not at all .

**Comment by DogancanYr** [comment]
@qtchaos Could you release this version as 1.4.1 on release and make it mandatory to run the program as an administrator?

**Comment by qtchaos** [comment]
Running any program under Administrator privileges is risky, and I would avoid this at any cost.

**Comment by DogancanYr** [comment]
You are right, this error has nothing to do with this problem anyway. Can you publish the latest change as a release?
