### ISSUE TITLE
Future exception was never retrieved

### ISSUE THREAD

**Issue by shobhit-jpg** [qtchaos/py_mega_account_generator#26]
HOPE! You are doing fine.

been facing some error ! 

Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error (Target.sendMessageToTarget): No session with given id')>
pyppeteer.errors.NetworkError: Protocol error (Target.sendMessageToTarget): No session with given id
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error (Target.sendMessageToTarget): No session with given id')>
pyppeteer.errors.NetworkError: Protocol error (Target.sendMessageToTarget): No session with given id
Traceback (most recent call last):
  File "D:\accountgenerator\py_mega_account_generator-master\main.py", line 155, in <module>
    asyncio.run(register(credentials, executable_path, config))
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\accountgenerator\py_mega_account_generator-master\main.py", line 114, in register
    await initial_setup(context, message, credentials)
  File "D:\accountgenerator\py_mega_account_generator-master\utilities\web.py", line 44, in initial_setup
    await confirm_page.waitForSelector("#freeStart", timeout=10000)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\frame_manager.py", line 855, in __await__
    raise result
pyppeteer.errors.TimeoutError: Waiting for selector "#freeStart" failed: timeout 10000ms exceeds.

![Screenshot 2024-01-23 195319](https://github.com/qtchaos/py_mega_account_generator/assets/72405851/c5ba5e0c-4d69-4a7f-b26a-ddb0dbf1f9b6)

**and is there a way to create multiple account without giving any filename !!**

**Comment by qtchaos** [comment]
You can use `python main.py -l 5` to generate multiple accounts without uploading a file. 

Does this issue occur every time?

**Comment by shobhit-jpg** [comment]
YES !

**Comment by shobhit-jpg** [comment]
If you want more information i can provide whenever i try generating accounts it gets the same error after te message **FOUND MAIL !** . you have any idea what might be the case or what does future exception means

**Comment by qtchaos** [comment]
Either the site is slow or your internet is slow, trying again a few times or waiting a bit should fix this. Other than that can't help you much, there is no issues in the code.
