### ISSUE TITLE
pyppeteer.errors.TimeoutError: Waiting for selector "#freeStart" failed: timeout 10000ms exceeds.

### ISSUE THREAD

**Issue by lakshits11** [qtchaos/py_mega_account_generator#30]
```
Please enter the path to a Chromium based browser's executable: C:\Program Files\Google\Chrome\Application\chrome.exe
Found executable!
Registered account successfully!
Retrieved mail successfully!
Found mail!
Traceback (most recent call last):
  File "C:\Users\Lakshit\Desktop\py_mega_account_generator\main.py", line 155, in <module>
    asyncio.run(register(credentials, executable_path, config))
  File "C:\Users\Lakshit\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Lakshit\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Lakshit\Desktop\py_mega_account_generator\main.py", line 114, in register
    await initial_setup(context, message, credentials)
  File "C:\Users\Lakshit\Desktop\py_mega_account_generator\utilities\web.py", line 44, in initial_setup
    await confirm_page.waitForSelector("#freeStart", timeout=10000)
  File "C:\Users\Lakshit\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\frame_manager.py", line 855, in __await__
    raise result
pyppeteer.errors.TimeoutError: Waiting for selector "#freeStart" failed: timeout 10000ms exceeds.
```

**Comment by qtchaos** [comment]
Either the site is slow or your internet is slow, trying again a few times or waiting a bit should fix this.
